name: Deploy to EC2 

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- EC2: 배포 프로세스 시작 ---"
            cd /home/ubuntu/movie-reservation-platform
            
            echo "1. 최신 dev 브랜치 코드 pull"
            git pull origin dev 
            
            echo "2. 환경 변수 로드"
            source /home/ubuntu/env.sh
            
            echo "3. 기존 애플리케이션 프로세스 종료"
            pkill -9 -f "java -jar" || true 
            
            sleep 5
            
            echo "4. Maven 빌드 (clean package)"
            mvn clean package -DskipTests 
            
            echo "5. 새로운 애플리케이션 실행"
            JAR_FILE=$(ls -tr /home/ubuntu/movie-reservation-platform/target/*.jar | grep -v '.original' | tail -n 1)
            nohup java -jar $JAR_FILE > /home/ubuntu/app.log 2>&1 &
            echo "> $JAR_FILE 백그라운드 실행 완료. (로그: /home/ubuntu/app.log)"
            
            echo "--- 배포 완료 ---"
